//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3PMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehirler
    {
        public Sehirler()
        {
            this.Ilcelers = new HashSet<Ilceler>();
        }
    
        public int SehirId { get; set; }
        public string SehirAdi { get; set; }
        public byte PlakaNo { get; set; }
        public int TelefonKodu { get; set; }
        public int RowNumber { get; set; }
    
        public virtual ICollection<Ilceler> Ilcelers { get; set; }
    }
}
